### ISSUE TITLE
docker 镜像无法启动

### ISSUE THREAD

**Issue by iovejieba** [mikutechnology/nas-tools-jackett#1]
看日志输出 貌似....索引器支持库 没补全...

**Comment by mikutechnology** [comment]
这只是初版，bug很多的，我还在修复，不建议使用

**Comment by naoki66** [comment]
ModuleNotFoundError: No module named 'web.backend.user'  也起不来

**Comment by mikutechnology** [comment]
已经添加这个库上去了，正在编译，建议你把镜像删除重新拉

**Comment by mikutechnology** [comment]
docker镜像有问题，用源码启动就没问题，建议使用源码
